import type { LayerData, SemanticId } from "./types.ts";
import type { TextLayout } from "./editable-text.ts";
/**
 * 漸層填色。from／to 是 #rrggbb 或 #rrggbbaa（可帶透明度）。
 * vertical 上→下、horizontal 左→右、diagonal 左上→右下、radial 由中間往外。
 */
export type ShapeGradient = { axis: "horizontal" | "vertical" | "diagonal" | "radial"; from: string; to: string };
export type ShapeKind = "rect" | "ellipse" | "line" | "icon" | "triangle" | "polygon" | "star" | "diamond";
export type ShapeSpec = { kind: ShapeKind; fill: string; stroke: string; strokeWidth: number; radius?: number; icon?: string; sides?: number; gradient?: ShapeGradient; softness?: number };

/**
 * 文字的分段樣式：用字元索引標出哪一段要換字級／顏色／字重。
 *
 * 之前一個文字圖層只有一組樣式，整串字共用，所以「只把某個字放大」做不到。
 * 用區間而不是逐字存，是因為使用者改字之後索引要跟著移動，區間比較好維護，
 * 也不會讓每個字都帶一份樣式把 JSON 撐大。
 *
 * start／end 是半開區間 [start, end)，對應 text 的字元索引。
 */
export type TextRun = { start: number; end: number; fontSize?: number; color?: string; fontWeight?: number };

export type TextFx = { gradient?: [string, string] | null; strokeColor?: string; strokeW?: number; shadow?: boolean; italic?: boolean; letterSpacing?: number;
  warp?: "none" | "arc-up" | "arc-down" | "wave"; warpAmount?: number; waveCount?: number };
export type SavedLayer = {
  id: string; name: string; type: LayerData["type"]; zIndex: number;
  x: number; y: number; w: number; h: number; rotation: number; visible: boolean; opacity: number; locked: boolean;
  image?: string;                     // image layers: persistent URL (or data: fallback)
  isArt?: boolean;                    // image layer generated by AI 文字藝術字（可再 AI 微調）
  artRefImage?: string;               // 生成時用的風格參考圖（data URL）
  isText?: boolean; text?: string; color?: string; fontSize?: number; fontFamily?: string; fontWeight?: number; align?: "left" | "center" | "right";
  fx?: TextFx | null;
  textLayout?: TextLayout;
  runs?: TextRun[];                   // 分段樣式（只把某幾個字放大／換色）
  shape?: { kind: ShapeKind; fill: string; stroke: string; strokeWidth: number; radius?: number; icon?: string; sides?: number; gradient?: ShapeGradient; softness?: number };
  groupId?: string | null;
  /**
   * 剪裁遮色片：這個圖層只顯示在指定形狀圖層的輪廓裡（像 Canva 的相框）。
   * 存的是形狀圖層的 id；形狀被刪掉就等於沒有剪裁。
   */
  clipTo?: string | null;
};
export function savedToLayerData(sl: SavedLayer): LayerData {
  const semanticId: SemanticId = sl.type === "independent_text" ? "text" : (sl.type as SemanticId);
  return {
    id: sl.id, type: sl.type, name: sl.name, semanticId, instanceId: sl.id, parentId: null,
    bbox: { x: sl.x, y: sl.y, w: sl.w, h: sl.h }, mask: null,
    image: sl.isText ? null : (sl.image ?? null),
    x: sl.x, y: sl.y, width: sl.w, height: sl.h, rotation: sl.rotation,
    zIndex: sl.zIndex, confidence: 1, source: "generated", editable: true,
    embeddedText: [], children: [],
    meta: {
      visible: sl.visible, locked: sl.locked, opacity: sl.opacity, groupId: sl.groupId ?? null,
      ...(sl.clipTo ? { clipTo: sl.clipTo } : {}),
      ...(sl.isText ? { style: { text: sl.text, fontSizePx: sl.fontSize, fontWeight: sl.fontWeight, color: sl.color, align: sl.align, fontFamily: sl.fontFamily, fx: sl.fx ?? null, ...(sl.textLayout ? { layout: sl.textLayout } : {}), ...(sl.runs ? { runs: sl.runs } : {}) }, textObject: { text: sl.text } } : {}),
      ...(sl.isArt ? { isArt: true, artText: sl.text ?? "", ...(sl.artRefImage ? { artRefImage: sl.artRefImage } : {}) } : {}),
      ...(sl.shape ? { shape: sl.shape } : {}),
    },
  };
}
